import type {
  AssetCategory,
  AssetDefinition,
  AssetSubcategory,
  NailLayer,
} from "./types";

export const ASSET_CATEGORIES: readonly { value: AssetCategory; label: string }[] = [
  { value: "design", label: "Design" },
  { value: "3d", label: "3D" },
  { value: "charms", label: "Charms" },
  { value: "chrome", label: "Chrome" },
] as const;

export const ASSET_SUBCATEGORY_LABELS: Readonly<Record<AssetSubcategory, string>> = {
  bows: "Bows",
  "french-tips": "French tips",
  aura: "Aura",
  ombre: "Ombre",
  florals: "Florals",
  swirls: "Swirls",
  stars: "Stars",
  hearts: "Hearts",
  "animal-prints": "Animal prints",
  patterns: "Patterns",
  "gel-swirls": "Gel swirls",
  flowers: "Flowers",
  bubbles: "Bubbles",
  shells: "Shells",
  pearls: "Pearls",
  rhinestones: "Rhinestones",
  gems: "Gems",
  chains: "Chains",
  "caviar-beads": "Caviar beads",
  gold: "Gold",
  silver: "Silver",
  "isolated-elements": "Elements",
};

const WHITE = "#ffffff";
const BLUSH = "#f4c3d3";
const LAVENDER = "#9573e4";
const GOLD = "#c9a45f";
const SILVER = "#aeb2ba";

export const ASSET_DEFINITIONS: readonly AssetDefinition[] = [
  {
    id: "design-soft-bow",
    name: "Soft bow",
    category: "design",
    subcategory: "bows",
    tags: ["ribbon", "romantic", "coquette"],
    defaultColor: BLUSH,
    secondaryColor: WHITE,
    defaultWidth: 46,
    defaultHeight: 34,
    tintable: true,
    elements: [
      { type: "path", d: "M50 48 C34 27 12 29 16 50 C20 68 37 66 50 55 Z", fill: "primary" },
      { type: "path", d: "M50 48 C66 27 88 29 84 50 C80 68 63 66 50 55 Z", fill: "primary" },
      { type: "circle", cx: 50, cy: 51, r: 9, fill: "secondary" },
      { type: "path", d: "M45 58 L35 88 L51 74 L50 57 Z M55 58 L65 88 L49 74 L50 57 Z", fill: "primary" },
    ],
  },
  {
    id: "design-french-curve",
    name: "French curve",
    category: "design",
    subcategory: "french-tips",
    tags: ["tip", "classic", "outline"],
    defaultColor: WHITE,
    secondaryColor: BLUSH,
    defaultWidth: 76,
    defaultHeight: 30,
    tintable: true,
    elements: [
      { type: "path", d: "M9 24 Q50 58 91 24 L91 45 Q50 76 9 45 Z", fill: "primary" },
    ],
  },
  {
    id: "design-lilac-aura",
    name: "Lilac aura",
    category: "design",
    subcategory: "aura",
    tags: ["glow", "halo", "soft"],
    defaultColor: LAVENDER,
    secondaryColor: BLUSH,
    defaultWidth: 64,
    defaultHeight: 64,
    tintable: true,
    elements: [
      { type: "circle", cx: 50, cy: 50, r: 40, fill: "primary", opacity: 0.18 },
      { type: "circle", cx: 50, cy: 50, r: 28, fill: "primary", opacity: 0.34 },
      { type: "circle", cx: 50, cy: 50, r: 16, fill: "secondary", opacity: 0.72 },
    ],
  },
  {
    id: "design-cloud-ombre",
    name: "Cloud ombre",
    category: "design",
    subcategory: "ombre",
    tags: ["gradient", "fade", "airbrush"],
    defaultColor: BLUSH,
    secondaryColor: WHITE,
    defaultWidth: 70,
    defaultHeight: 88,
    tintable: true,
    elements: [
      { type: "ellipse", cx: 50, cy: 72, rx: 38, ry: 22, fill: "primary", opacity: 0.2 },
      { type: "ellipse", cx: 50, cy: 51, rx: 31, ry: 24, fill: "primary", opacity: 0.4 },
      { type: "ellipse", cx: 50, cy: 30, rx: 22, ry: 18, fill: "primary", opacity: 0.68 },
    ],
  },
  {
    id: "design-daisy-cluster",
    name: "Daisy cluster",
    category: "design",
    subcategory: "florals",
    tags: ["flower", "petals", "spring"],
    defaultColor: WHITE,
    secondaryColor: GOLD,
    defaultWidth: 42,
    defaultHeight: 42,
    tintable: true,
    elements: [
      { type: "ellipse", cx: 50, cy: 25, rx: 11, ry: 20, fill: "primary" },
      { type: "ellipse", cx: 74, cy: 43, rx: 11, ry: 20, fill: "primary" },
      { type: "ellipse", cx: 65, cy: 72, rx: 11, ry: 20, fill: "primary" },
      { type: "ellipse", cx: 35, cy: 72, rx: 11, ry: 20, fill: "primary" },
      { type: "ellipse", cx: 26, cy: 43, rx: 11, ry: 20, fill: "primary" },
      { type: "circle", cx: 50, cy: 50, r: 12, fill: "secondary" },
    ],
  },
  {
    id: "design-ribbon-swirl",
    name: "Ribbon swirl",
    category: "design",
    subcategory: "swirls",
    tags: ["line", "wave", "abstract"],
    defaultColor: LAVENDER,
    secondaryColor: WHITE,
    defaultWidth: 65,
    defaultHeight: 78,
    tintable: true,
    elements: [
      { type: "path", d: "M18 76 C84 70 14 35 78 20 C91 17 89 7 76 8", fill: "none", stroke: "primary", strokeWidth: 10 },
    ],
  },
  {
    id: "design-twinkle-star",
    name: "Twinkle star",
    category: "design",
    subcategory: "stars",
    tags: ["celestial", "sparkle", "night"],
    defaultColor: WHITE,
    secondaryColor: LAVENDER,
    defaultWidth: 30,
    defaultHeight: 38,
    tintable: true,
    elements: [
      { type: "path", d: "M50 5 L60 38 L94 50 L60 62 L50 95 L40 62 L6 50 L40 38 Z", fill: "primary" },
    ],
  },
  {
    id: "design-puffy-heart",
    name: "Puffy heart",
    category: "design",
    subcategory: "hearts",
    tags: ["love", "sweet", "romantic"],
    defaultColor: BLUSH,
    secondaryColor: WHITE,
    defaultWidth: 34,
    defaultHeight: 31,
    tintable: true,
    elements: [
      { type: "path", d: "M50 88 C39 74 12 58 12 34 C12 10 42 7 50 27 C58 7 88 10 88 34 C88 58 61 74 50 88 Z", fill: "primary" },
    ],
  },
  {
    id: "design-leopard-spots",
    name: "Leopard spots",
    category: "design",
    subcategory: "animal-prints",
    tags: ["leopard", "wild", "spots"],
    defaultColor: "#6e5045",
    secondaryColor: GOLD,
    defaultWidth: 58,
    defaultHeight: 72,
    tintable: true,
    elements: [
      { type: "circle", cx: 26, cy: 27, r: 13, fill: "none", stroke: "primary", strokeWidth: 8 },
      { type: "circle", cx: 70, cy: 43, r: 16, fill: "none", stroke: "primary", strokeWidth: 9 },
      { type: "circle", cx: 34, cy: 76, r: 12, fill: "none", stroke: "primary", strokeWidth: 8 },
      { type: "circle", cx: 82, cy: 84, r: 5, fill: "primary" },
    ],
  },
  {
    id: "design-checker-wave",
    name: "Checker wave",
    category: "design",
    subcategory: "patterns",
    tags: ["checker", "graphic", "retro"],
    defaultColor: LAVENDER,
    secondaryColor: WHITE,
    defaultWidth: 66,
    defaultHeight: 66,
    tintable: true,
    elements: [
      { type: "path", d: "M8 8 H38 V38 H8 Z M38 38 H68 V68 H38 Z M68 8 H92 V38 H68 Z M8 68 H38 V92 H8 Z M68 68 H92 V92 H68 Z", fill: "primary" },
    ],
  },
  {
    id: "3d-gel-ripple",
    name: "Gel ripple",
    category: "3d",
    subcategory: "gel-swirls",
    tags: ["raised", "gel", "wave"],
    defaultColor: WHITE,
    secondaryColor: BLUSH,
    defaultWidth: 58,
    defaultHeight: 80,
    tintable: true,
    elements: [
      { type: "path", d: "M16 82 C88 65 15 42 82 15", fill: "none", stroke: "primary", strokeWidth: 15 },
      { type: "path", d: "M18 78 C84 62 20 43 78 18", fill: "none", stroke: "white", strokeWidth: 4, opacity: 0.62 },
    ],
  },
  {
    id: "3d-sculpted-flower",
    name: "Sculpted flower",
    category: "3d",
    subcategory: "flowers",
    tags: ["petal", "raised", "flower"],
    defaultColor: BLUSH,
    secondaryColor: WHITE,
    defaultWidth: 48,
    defaultHeight: 48,
    tintable: true,
    elements: [
      { type: "ellipse", cx: 50, cy: 26, rx: 13, ry: 23, fill: "primary" },
      { type: "ellipse", cx: 72, cy: 49, rx: 13, ry: 23, fill: "primary" },
      { type: "ellipse", cx: 50, cy: 73, rx: 13, ry: 23, fill: "primary" },
      { type: "ellipse", cx: 28, cy: 49, rx: 13, ry: 23, fill: "primary" },
      { type: "circle", cx: 50, cy: 50, r: 11, fill: "secondary" },
    ],
  },
  {
    id: "3d-clear-bubbles",
    name: "Clear bubbles",
    category: "3d",
    subcategory: "bubbles",
    tags: ["water", "clear", "drops"],
    defaultColor: WHITE,
    secondaryColor: LAVENDER,
    defaultWidth: 44,
    defaultHeight: 62,
    tintable: true,
    elements: [
      { type: "circle", cx: 35, cy: 30, r: 19, fill: "primary", opacity: 0.55, stroke: "white", strokeWidth: 4 },
      { type: "circle", cx: 68, cy: 57, r: 25, fill: "primary", opacity: 0.42, stroke: "white", strokeWidth: 4 },
      { type: "circle", cx: 28, cy: 82, r: 11, fill: "primary", opacity: 0.48, stroke: "white", strokeWidth: 3 },
    ],
  },
  {
    id: "3d-mini-shell",
    name: "Mini shell",
    category: "3d",
    subcategory: "shells",
    tags: ["sea", "summer", "sculpted"],
    defaultColor: "#f8f2e7",
    secondaryColor: BLUSH,
    defaultWidth: 42,
    defaultHeight: 36,
    tintable: true,
    elements: [
      { type: "path", d: "M12 76 Q13 21 50 12 Q87 21 88 76 Q50 96 12 76 Z", fill: "primary" },
      { type: "line", x1: 50, y1: 18, x2: 50, y2: 82, stroke: "secondary", strokeWidth: 4 },
      { type: "line", x1: 29, y1: 29, x2: 37, y2: 84, stroke: "secondary", strokeWidth: 4 },
      { type: "line", x1: 71, y1: 29, x2: 63, y2: 84, stroke: "secondary", strokeWidth: 4 },
    ],
  },
  {
    id: "charm-pearl-trio",
    name: "Pearl trio",
    category: "charms",
    subcategory: "pearls",
    tags: ["pearl", "classic", "cluster"],
    defaultColor: "#f8f2e7",
    secondaryColor: WHITE,
    defaultWidth: 42,
    defaultHeight: 42,
    tintable: false,
    elements: [
      { type: "circle", cx: 32, cy: 34, r: 20, fill: "primary", stroke: "white", strokeWidth: 4 },
      { type: "circle", cx: 68, cy: 34, r: 20, fill: "primary", stroke: "white", strokeWidth: 4 },
      { type: "circle", cx: 50, cy: 68, r: 22, fill: "primary", stroke: "white", strokeWidth: 4 },
    ],
  },
  {
    id: "charm-rhinestone",
    name: "Rhinestone",
    category: "charms",
    subcategory: "rhinestones",
    tags: ["crystal", "sparkle", "stone"],
    defaultColor: WHITE,
    secondaryColor: LAVENDER,
    defaultWidth: 28,
    defaultHeight: 28,
    tintable: false,
    elements: [
      { type: "path", d: "M50 4 L94 50 L50 96 L6 50 Z", fill: "primary", stroke: "secondary", strokeWidth: 4 },
      { type: "path", d: "M50 4 L67 50 L50 96 L33 50 Z", fill: "secondary", opacity: 0.34 },
    ],
  },
  {
    id: "charm-prism-gem",
    name: "Prism gem",
    category: "charms",
    subcategory: "gems",
    tags: ["gem", "jewel", "faceted"],
    defaultColor: LAVENDER,
    secondaryColor: WHITE,
    defaultWidth: 36,
    defaultHeight: 42,
    tintable: true,
    elements: [
      { type: "path", d: "M24 14 L76 14 L94 46 L50 92 L6 46 Z", fill: "primary", stroke: "white", strokeWidth: 4 },
      { type: "path", d: "M24 14 L50 46 L76 14 M6 46 H94 M50 46 V92", fill: "none", stroke: "white", strokeWidth: 3, opacity: 0.7 },
    ],
  },
  {
    id: "charm-fine-chain",
    name: "Fine chain",
    category: "charms",
    subcategory: "chains",
    tags: ["chain", "metal", "link"],
    defaultColor: GOLD,
    secondaryColor: WHITE,
    defaultWidth: 24,
    defaultHeight: 74,
    tintable: true,
    metallic: "gold",
    elements: [
      { type: "ellipse", cx: 50, cy: 16, rx: 17, ry: 11, fill: "none", stroke: "primary", strokeWidth: 7 },
      { type: "ellipse", cx: 50, cy: 38, rx: 17, ry: 11, fill: "none", stroke: "primary", strokeWidth: 7 },
      { type: "ellipse", cx: 50, cy: 60, rx: 17, ry: 11, fill: "none", stroke: "primary", strokeWidth: 7 },
      { type: "ellipse", cx: 50, cy: 82, rx: 17, ry: 11, fill: "none", stroke: "primary", strokeWidth: 7 },
    ],
  },
  {
    id: "charm-metal-bow",
    name: "Metal bow",
    category: "charms",
    subcategory: "bows",
    tags: ["bow", "metal", "coquette"],
    defaultColor: SILVER,
    secondaryColor: WHITE,
    defaultWidth: 45,
    defaultHeight: 32,
    tintable: true,
    metallic: "silver",
    elements: [
      { type: "path", d: "M47 48 C28 16 7 27 12 52 C17 76 37 66 50 55 C63 66 83 76 88 52 C93 27 72 16 53 48 Z", fill: "primary", stroke: "white", strokeWidth: 3 },
      { type: "circle", cx: 50, cy: 51, r: 9, fill: "secondary" },
    ],
  },
  {
    id: "charm-caviar-curve",
    name: "Caviar curve",
    category: "charms",
    subcategory: "caviar-beads",
    tags: ["beads", "micro", "curve"],
    defaultColor: GOLD,
    secondaryColor: WHITE,
    defaultWidth: 52,
    defaultHeight: 30,
    tintable: true,
    metallic: "gold",
    elements: [
      { type: "circle", cx: 12, cy: 67, r: 7, fill: "primary" },
      { type: "circle", cx: 25, cy: 51, r: 7, fill: "primary" },
      { type: "circle", cx: 42, cy: 40, r: 7, fill: "primary" },
      { type: "circle", cx: 60, cy: 38, r: 7, fill: "primary" },
      { type: "circle", cx: 77, cy: 46, r: 7, fill: "primary" },
      { type: "circle", cx: 90, cy: 62, r: 7, fill: "primary" },
    ],
  },
  {
    id: "charm-star-stud",
    name: "Star stud",
    category: "charms",
    subcategory: "stars",
    tags: ["star", "stud", "celestial"],
    defaultColor: GOLD,
    secondaryColor: WHITE,
    defaultWidth: 28,
    defaultHeight: 28,
    tintable: true,
    metallic: "gold",
    elements: [
      { type: "path", d: "M50 4 L61 37 L96 37 L68 57 L79 92 L50 71 L21 92 L32 57 L4 37 L39 37 Z", fill: "primary", stroke: "white", strokeWidth: 3 },
    ],
  },
  {
    id: "chrome-gold-swoop",
    name: "Gold swoop",
    category: "chrome",
    subcategory: "gold",
    tags: ["gold", "line", "chrome"],
    defaultColor: GOLD,
    secondaryColor: WHITE,
    defaultWidth: 58,
    defaultHeight: 68,
    tintable: true,
    metallic: "gold",
    elements: [
      { type: "path", d: "M18 85 C14 45 39 13 84 12", fill: "none", stroke: "primary", strokeWidth: 13 },
      { type: "path", d: "M23 82 C21 49 42 21 79 17", fill: "none", stroke: "white", strokeWidth: 3, opacity: 0.58 },
    ],
  },
  {
    id: "chrome-silver-orbit",
    name: "Silver orbit",
    category: "chrome",
    subcategory: "silver",
    tags: ["silver", "ring", "chrome"],
    defaultColor: SILVER,
    secondaryColor: WHITE,
    defaultWidth: 42,
    defaultHeight: 42,
    tintable: true,
    metallic: "silver",
    elements: [
      { type: "ellipse", cx: 50, cy: 50, rx: 39, ry: 22, fill: "none", stroke: "primary", strokeWidth: 11 },
      { type: "ellipse", cx: 50, cy: 47, rx: 32, ry: 16, fill: "none", stroke: "white", strokeWidth: 3, opacity: 0.62 },
    ],
  },
  {
    id: "chrome-liquid-drop",
    name: "Liquid drop",
    category: "chrome",
    subcategory: "isolated-elements",
    tags: ["drop", "isolated", "molten"],
    defaultColor: SILVER,
    secondaryColor: WHITE,
    defaultWidth: 34,
    defaultHeight: 48,
    tintable: true,
    metallic: "silver",
    elements: [
      { type: "path", d: "M50 5 C46 26 18 47 18 67 C18 88 34 96 50 96 C66 96 82 88 82 67 C82 47 54 26 50 5 Z", fill: "primary", stroke: "white", strokeWidth: 4 },
      { type: "ellipse", cx: 39, cy: 58, rx: 8, ry: 14, fill: "white", opacity: 0.55 },
    ],
  },
] as const;

export const ASSET_BY_ID = new Map(ASSET_DEFINITIONS.map((asset) => [asset.id, asset]));

export function createLayerFromAsset(asset: AssetDefinition, id: string): NailLayer {
  return {
    id,
    assetId: asset.id,
    name: asset.name,
    kind: asset.category,
    color: asset.defaultColor,
    x: 50,
    y: 90,
    width: asset.defaultWidth,
    height: asset.defaultHeight,
    rotation: 0,
    opacity: 1,
    tintable: asset.tintable,
    metallic: asset.metallic,
  };
}
